const ROLE_ADMIN = 5;
const ROLE_TRANSACTION_POINT_MANAGER = 1;
const ROLE_TRANSACTION_POINT_STAFF = 2;
const ROLE_TRANSIT_POINT_MANAGER = 3;
const ROLE_TRANSIT_POINT_STAFF = 4;

const ROLE_TRANSACTION_POINT = 1;
const ROLE_TRANSIT_POINT = 2;

module.exports = {
    ROLE_ADMIN,
    ROLE_TRANSACTION_POINT_MANAGER,
    ROLE_TRANSACTION_POINT_STAFF,
    ROLE_TRANSIT_POINT_MANAGER,
    ROLE_TRANSIT_POINT_STAFF,
    ROLE_TRANSIT_POINT,
    ROLE_TRANSACTION_POINT
}
